<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TL Default</title>

    <?php // include_once "headers/_bootstrap_header.phtml"; ?>

    <?php include_once "headers/_semantics_header.phtml"; ?>

    <!-- Custom CSS file -->
    <link rel="stylesheet" href="public/css/main.css">

</head>
<body>

    <div  style="text-align: center">
        <h1><br></h1>
        <img src="https://www.spreadshirt.com/image-server/v1/designs/12482951,width=178,height=178/goat-head-with-pentagram-inverted.png" />
        <h1>Tiny Lord</h1>

        <!-- fetching controller data example -->
        <?php

        foreach($data as $ar){
            echo '<p>'.$ar.'</p>';
        }

        // md file parser
        /*if(file_exists(__DIR__.'/../../../../README.md')){
            require_once __DIR__.'/../../lib/Parsedown.php';
            $Parsedown = new Parsedown();
            echo "<div style='text-align: left'>".$Parsedown->text(file_get_contents(__DIR__.'/../../../../README.md'))."</div>";
        }*/

        ?>

    </div>

    <?php //include_once "footers/_bootstrap_footer.phtml"; ?>

    <?php include_once "footers/_semantics_footer.phtml"; ?>

</body>
</html>
